#
# Travis Setup
#
dist: trusty

# faster builds on new travis setup not using sudo
sudo: required
group: edge

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    #- php: 7.2
    - php: 7.1

install:
  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

  # setup PHP extension
  - tests/data/travis/image.sh

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
    fi
  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
  - |
    if [ $TRAVIS_PHP_VERSION == 7.2 ]; then
      echo 'Disabled DEPRECATED notifications for PHP 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi

script:
  # PHP tests
  - vendor/bin/codecept --verbose run --coverage --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - mv ./tests/_output/coverage.xml ./coverage.xml
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
